apiVersion: v1
kind: Service
metadata:
  name: carefe-production
  labels:
    app: carefe-production
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: carefe-production
