apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carebe-production
  labels:
    application: carebe-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: carebe-production
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
