apiVersion: v1
kind: Service
metadata:
  name: carebe-production
  labels:
    app: carebe-production
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: carebe-production
