apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-production
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {

      access_log  /dev/stdout;

      server {
        listen 80 ;
        server_name _;

        if ($http_x_forwarded_proto != "https") {
          return 301 https://$host$request_uri;
        }

        access_log /dev/stdout;
        error_log /dev/stdout;

        location /api {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://carebe-production:9000;
        }

        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://carefe-production;
        }
      }
    }

