apiVersion: v1
kind: Service
metadata:
  name: care-nginx-production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:<<account_number>>:certificate/<<cert_identifier>>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: care-nginx-production
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    app: care-nginx-production
