apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-production
  labels:
    app: redis-cache-production
spec:
  selector:
    matchLabels:
      app: redis-cache-production
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-cache-production
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 2000Mi
        ports:
        - containerPort: 6379

